### ISSUE TITLE
CSS基础测试1：卡片式布局

### ISSUE THREAD

**Issue by wingmeng** [wingmeng/front-end-quiz#1]
#### 题目：
![image](https://user-images.githubusercontent.com/9009389/53154517-eebaf400-35f5-11e9-9f00-6e7e3e66f74b.png)

----

#### 我的答案：
``` css
dl {
    max-width: 400px;
    padding: 5px 15px;
    line-height: 2;
    box-sizing: border-box;
    border: 1px solid #ccc;
    box-shadow: 1px 1px 0 rgba(0,0,0,.15);
}

dt {display: inline;}

/* 灵感来自《CSS揭秘》P116 */
dd + dt::before {
    content: '\A';
    white-space: pre;
}

dd {
    float: right;
    margin: 0;
}
```
![demo min](https://user-images.githubusercontent.com/9009389/51232087-a8dc9180-19a0-11e9-97ea-bc2714e8cecb.png)

**Comment by wingmeng** [comment]
#### 不足之处：

1. 依赖行高来对齐，局限性比较大，如右侧多行时，布局会错位

**Comment by wingmeng** [comment]
#### 最佳实践1：[DEMO](https://codepen.io/wingmeng/pen/yrwNQw)
> 理由：代码量少，容错性最强，语义最佳，维护成本极低

```css
dl {
  display: grid;
  grid-template-columns: auto 1fr;
  grid-column-gap: 1em;
}

dd {text-align: right;}
```

#### 最佳实践2：[DEMO](https://codepen.io/wingmeng/pen/rbRVbB)
> 理由：代码量非常少，兼容性非常好

```css
dd {
  /* 5em = 左侧汉字最大长度 + 1em（间距） */
  margin: -1.5em 0 0 5em;
  text-align: right;
}
```
