### ISSUE TITLE
CSS基础测试7：紧贴底部的页脚

### ISSUE THREAD

**Issue by wingmeng** [wingmeng/front-end-quiz#16]
#### 题目：
![image](https://user-images.githubusercontent.com/9009389/59149325-ad384280-8a46-11e9-917f-1b2ccc99e0cb.png)

----

#### 我的回答：
[> 在线 Demo <](https://codepen.io/wingmeng/pen/RmOmdy)

```css
body {margin: 0;}
main, content, footer {display: block;}

.container {
  display: flex;
  flex-flow: column;
  min-height: 100vh;  /* 不设置固定高度 */
}

.content {flex: 1;}

.footer {
  color: #fff;
  background: #555;
}
```

**Comment by wingmeng** [comment]
#### 自我评分：`一般`
> 优秀、良好、一般、差劲

#### 不足之处：

1. 无突出亮点；
2. 语义化上有待加强。

#### 学习收获：

1. `margin: auto` 的用法。

**Comment by wingmeng** [comment]
#### 最佳实践：

```css
body {margin: 0;}

.container {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

.content {margin-top: auto;}

.footer {
  color: #fff;
  background: #555;
}
```
